# Generated by Django 3.2.5 on 2021-07-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='timestamp',
            field=models.CharField(default='01:27', max_length=100),
        ),
    ]
