# Generated by Django 3.2.5 on 2021-09-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taker', '0002_note_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='youtube_id',
            field=models.CharField(default='Y2_B7oKYoAU', max_length=100),
        ),
    ]
