# Generated by Django 3.2.5 on 2021-09-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taker', '0003_notebook_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='notebook_id',
            field=models.CharField(default='notebookID', max_length=100),
        ),
    ]
