# Generated by Django 3.2.5 on 2021-09-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taker', '0004_notebook_notebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='notebook_id',
            field=models.CharField(default='Randomly generated', max_length=100),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='youtube_id',
            field=models.CharField(default='Will fill automatically', max_length=100),
        ),
    ]
