# Generated by Django 4.1.2 on 2022-10-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taker', '0005_auto_20210919_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='privacy',
            field=models.CharField(default='Private', max_length=100),
        ),
    ]
