# Generated by Django 4.1.5 on 2023-04-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_taker', '0006_note_likes_notebook_description_notebook_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='privacy',
        ),
    ]
