# Generated by Django 4.1.5 on 2023-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taker', '0007_remove_note_likes_remove_notebook_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='raw_timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
